# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Vivado/lab_3/lab_3.cache/wt [current_project]
set_property parent.project_path F:/Vivado/lab_3/lab_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib F:/Vivado/lab_3/lab_3.srcs/sources_1/new/slow_blinky_module.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Vivado/lab_3/lab_3.srcs/constrs_1/imports/MyWork/Basys3_Master.xdc
set_property used_in_implementation false [get_files F:/Vivado/lab_3/lab_3.srcs/constrs_1/imports/MyWork/Basys3_Master.xdc]


synth_design -top slow_blinky_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef slow_blinky_module.dcp

catch { report_utilization -file slow_blinky_module_utilization_synth.rpt -pb slow_blinky_module_utilization_synth.pb }
