# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/sources_1/new/d_flip_flop.v
  C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/sources_1/new/my_slow_blinky_slower.v
  C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/sources_1/new/my_slow_blinky2.v
  C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/sources_1/new/my_slow_blinky1.v
  C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/sources_1/new/my_dff.v
  C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/sources_1/imports/Downloads/cliffgame.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/constrs_1/imports/Assign_4_final/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator.UER-PC/Documents/Vivado/Github/Assign_4_final/Assign_4_final.srcs/constrs_1/imports/Assign_4_final/Basys3_Master.xdc]


synth_design -top cliffgame -part xc7a35tcpg236-1


write_checkpoint -force -noxdef cliffgame.dcp

catch { report_utilization -file cliffgame_utilization_synth.rpt -pb cliffgame_utilization_synth.pb }
