set_property SRC_FILE_INFO {cfile:F:/Vivado/lab_3/lab_3.srcs/constrs_1/imports/MyWork/Basys3_Master.xdc rfile:../../../lab_3.srcs/constrs_1/imports/MyWork/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports CLOCK]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {A}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {LED}]
