# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.srcs/sources_1/new/my_dff.v}
  {C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.srcs/sources_1/new/slowclock.v}
  {C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.srcs/sources_1/new/my_singlepulse.v}
  {C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.srcs/sources_1/new/my_ledarr.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.srcs/constrs_1/imports/MyWork/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Administrator.UER-PC/OneDrive - National University of Singapore/Vivado/lab4/lab4.srcs/constrs_1/imports/MyWork/Basys3_Master.xdc}}]


synth_design -top my_ledarr -part xc7a35tcpg236-1


write_checkpoint -force -noxdef my_ledarr.dcp

catch { report_utilization -file my_ledarr_utilization_synth.rpt -pb my_ledarr_utilization_synth.pb }
